### ISSUE TITLE
Use devDependencies

### ISSUE THREAD

**Issue by sindresorhus** [DKunin/snake-cli-loader#1]
Hey. I noticed you have `ava` as a `dependency` in your package.json. This means anyone who installs this module would also install `ava`. You should instead put `ava` into [`devDependencies`](https://docs.npmjs.com/files/package.json#devdependencies).

I would recommend publishing a new patch version after doing this.

**Comment by DKunin** [comment]
Hey!

Dammit, I must use email notification, you wouldn't believe, that I just saw this issue.
Fixed it! Thanks!

Soon I'll update versions too.
